# Generated by Django 3.2.4 on 2021-07-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_with_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entering',
            options={'verbose_name': 'Прохождение', 'verbose_name_plural': 'Прохождение'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тесты', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RenameField(
            model_name='entering',
            old_name='quest_id',
            new_name='quest',
        ),
        migrations.RenameField(
            model_name='entering',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='entering',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_id',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testidforquest', to='site_with_tests.test'),
        ),
    ]
