# Generated by Django 3.2.4 on 2021-07-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_with_tests', '0002_auto_20210702_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='true_var',
        ),
        migrations.AddField(
            model_name='question',
            name='var1_isTrue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='var2_isTrue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='var3_isTrue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='var4_isTrue',
            field=models.BooleanField(default=False),
        ),
    ]
